### ISSUE TITLE
Link broken to find server_key on parsec website

### ISSUE THREAD

**Issue by jeremyadamsfisher** [cloudrig/CloudRIG#16] opened 2019-12-14 20:07 UTC
<img width="433" alt="s1" src="https://user-images.githubusercontent.com/12537747/70853967-63ac3280-1e83-11ea-8022-f3ebe11fe614.png">
<img width="839" alt="s2" src="https://user-images.githubusercontent.com/12537747/70853968-6444c900-1e83-11ea-9d56-36fbe4b91a86.png">

**Comment by phil-r** [comment] 2019-12-16 11:34
Duplicate of https://github.com/cloudrig/CloudRIG/issues/10

**Closed as completed** 2020-05-14 08:49 UTC
